@extends('layouts.user')

@section('title', 'Terms & Conditions | Poovar Boating Club')

@section('header')
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3 d-block " style="background:white; box-shadow:0 4px 12px rgba(0,0,0,.5);" data-navbar-on-scroll="data-navbar-on-scroll">

    <div class="container"><a class="navbar-brand" href="{{ route('user.index') }}"><img src="{{ asset('assets/img/logo-Fenlake-default.png') }}" alt="logo" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"> </span></button>
            <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto pt-2 pt-lg-0 font-base align-items-lg-center align-items-start">
                    <li class="nav-item px-3 px-xl-3"><a class="nav-link fw-medium" aria-current="page"
                            href="{{route('user.index')}}#service" style="color: black;">Services</a></li>
                    <li class="nav-item px-3 px-xl-3"><a class="nav-link fw-medium" aria-current="page"
                            href="{{route('user.index')}}#packages" style="color: black;">Packages</a></li>
                    <li class="nav-item px-3 px-xl-3"><a class="nav-link fw-medium" aria-current="page"
                            href="{{route('user.index')}}#gallery" style="color: black;">Gallery</a></li>
                    <li class="nav-item px-3 px-xl-3"><a class="nav-link fw-medium" aria-current="page"
                            href="{{route('user.index')}}#testimonial" style="color: black;">Testimonial</a></li>

                </ul>
                <a class="nav-link fw-medium tele fn-call-btn ms-lg-3"
                    href="tel:+919778500322">
                    <img src="{{ asset('assets/img/phone-call.png') }}" width="20" class="me-2" alt="">
                    Call Us: 97785 00322
                </a>
            </div>
    </div>
</nav>
@endsection
@section('content')

<section class="py-5" style="margin-top:120px;">
    <div class="container">

        <div class="row ">
            <div class="col-12 ">
                <h2>Terms &amp; Conditions</h2>
                <ol style="line-height:2.0;">
                    <li>
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </li>

                    <li>
                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong>https://fenlake.in</strong>, including the related mobile site and mobile application.
                    </li>

                    <li>
                        The Platform is owned by <strong>Poovar boating Club</strong>, a company incorporated under the Companies Act, 1956 with its registered office at <strong>Poovar - Uchakada Bypass, Rd, Poovar, Kerala 695506.</strong>
                    </li>

                    <li>
                        Your use of the Platform and the boat booking services is governed by these Terms &amp; Conditions and all applicable policies published on the Platform. By accessing the Platform, submitting an enquiry, making a booking, or availing any boating service, you agree to be bound by these Terms &amp; Conditions. These Terms may be updated from time to time without prior notice, and it is your responsibility to review them periodically.
                    </li>

                    <li>
                        For the purpose of these Terms of Use, wherever the context so requires your shall mean any natural or legal person who has agreed to become a costumer/guest on the Platform.
                    </li>

                    <li>
                        Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use, so please read the Terms of Use carefully before proceeding.
                    </li>

                    <li>
                        The use of Platform and availing of our Services is subject to the following Terms of Use:

                        <ul>
                            <li>
                                To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
                            </li>

                            <li>
                                Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                            </li>

                            <li>
                                Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
                            </li>

                            <li>
                                The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
                            </li>

                            <li>
                                You acknowledge that unauthorized use of the Platform and the Services may lead to action against you as per these Terms of Use or applicable laws.
                            </li>

                            <li>
                                You agree to pay us the charges associated with availing the boating Services.
                            </li>

                            <li>
                                You agree not to use the Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
                            </li>

                            <li>
                                You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.
                            </li>

                            <li>
                                You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
                            </li>

                            <li>
                                You shall indemnify and hold harmless Platform Owner, its affiliates, group companies and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights of a third party.
                            </li>

                            <li>
                                Not with standing anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                            </li>

                            <li>
                                These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
                            </li>

                            <li>
                                All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in and .
                            </li>

                            <li>
                                All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
                            </li>
                        </ul>
                    </li>
                </ol>
            </div>
        </div>




    </div>
</section>









@endsection